### ISSUE TITLE
speciates estimate for N sightings?

### ISSUE THREAD

**Issue by rlskoeser** [mikekestemont/copia#27]
I think the estimates from these methods are overly pessimistic for my data because some of the assumptions in the equations don't apply, and want to mitigate by calculating "species" estimate based on a separate estimate of missing activity ("sightings"). 

Is there a way to get this from the `species_accumulation` method or accumulation curve? Please advise.

**Comment by fbkarsdorp** [comment]
It's a bit hard to judge whether the methods would apply without any knowledge of the data, but I can say that the extent to which observations can be grouped into clear categories matters quite a bit.

By "pessimistic" you mean the model is overestimating, or underestimating? 

You could try the species accumulation procedure, indeed. But of course, it's based on the same assumptions. The `species_accumulation` in `richness.py` gives you both interpolated as well as extrapolated values. To speed things up, you can turn off the bootstrap (`n_iter`) and just use the `rarefaction_extrapolation` function from `stats.py`.

**Comment by rlskoeser** [comment]
I think the model is overestimating because the assumptions don't quite hold — I called it pessimistic because it means the percent of surviving is data is much lower than from our previous estimates (sorry, I see now how that was unclear without context!).

Thanks for the tips about how to try the accumulation method — I recognize the same assumptions will be embedded in the methods, but am curious what numbers I'll get since I already have an estimate of how many "sightings" we're missing.

The fact that the models don't fit our data exactly is ok for our work now which we're framing as speculative anyway  — we'll have opportunity to revisit these estimates, and maybe it will help move the conversation forward about what kinds of cultural data are appropriate for these models and how to group observations properly.

**Comment by fbkarsdorp** [comment]
I see, yes. it might also be interesting to see whether the estimates of the number of sightings match with your estimate, you could do something similar to what we've done for computing the number of missing documents:

```python
from copia.utils import survival_ratio

R = survival_ratio(abundance, method='minsample')
```

(Little warning, this might take some time.)

**Comment by rlskoeser** [comment]
I think it's ok to close this issue now. :-)  Thanks for the response.
