### ISSUE TITLE
survival_rate doesn't complete

### ISSUE THREAD

**Issue by KAKDH** [mikekestemont/copia#31]
Hi guys!

Running from IDLE 3.11.13 for Python 3.11.3 TK 8.6.12 on Mac M1, 2020, I cannot get the survival_rate function to complete. It runs and runs and never completes. 

I tied unsuccessfully running it in many shapes, such as: 
survival_ratio(abundance, method='chao1')
survival_ratio(abundance, method=“chao1”, n_iter=100, n_jobs=4)
survival_ratio(abundance, method=“chao1”, n_iter=10)

Anyone faces the same problem?
* The same issue when I try to reproduce the FB results following the workflow described in jupyter notebooks.

**Comment by fbkarsdorp** [comment]
This is resolved and wasn't an issue with the package.
