### ISSUE TITLE
Superfluous assertions

### ISSUE THREAD

**Issue by fbkarsdorp** [mikekestemont/copia#8]
All diversity functions use the same assertion statement:

https://github.com/mikekestemont/copia/blob/47c88046071a7121f2cfe8e49b193ceb9019e947/copia/richness.py#L29

If we hide these functions from the user, and direct them to only use the main interface function `diversity()`, we can remove all assertions and add one to the diversity function.

**Comment by mikekestemont** [comment]
Yes, I thought about that (it's also slower like this...), but then we don't guard the user from using the base functions with lists etc. Maybe that's ok.
